# Generated by Django 5.1.15 on 2026-09-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='can_manage_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servermember',
            name='can_manage_messages',
            field=models.BooleanField(default=False),
        ),
    ]
