# Generated by Django 5.1.15 on 2026-09-06 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100)),
                ('channel_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice')], default='TEXT', max_length=10)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='servers.server')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('server', 'name'), name='unique_channel_per_server')],
            },
        ),
    ]
